version: 0.2

phases:
runtime: nodejs18
  install:
    commands:
      - echo "Installing dependencies..""
      - npm install
  build:
    commands:
      - echo "Running tests...""
      - npm test
